name: Release

on:
  release:
     types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: deps
      run: sudo apt-get install libgcrypt20-dev xa65
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        ref: ${{ github.ref }}
    - name: bootstrap
      run: autoreconf -vfi
    - name: configure
      run: ./configure
    - name: make dist
      id: package-generator
      run: |
        make dist
        RELEASE_TARBALL=$(ls libsidplayfp-*.tar.gz)
        echo ::set-output name=filename::${RELEASE_TARBALL}
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: ${{ steps.package-generator.outputs.filename }} application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
